### ISSUE TITLE
NullPointerException when running pspg in sqlcl

### ISSUE THREAD

**Issue by talek** [okbob/pspg#228]
Hello,

I'm trying to setup pspg in my sqlcl environment and I get the following error:

```
SQL> set sqlformat ansiconsole
SQL> select * from dual;

DUMMY
________
X

SQL> pspg select * from dual;
2023-07-07 10:43:42.209 SEVERE oracle.dbtools.raptor.newscriptrunner.ScriptExecutor run oracle.dbtools.raptor.newscriptrunner.SQL.executeQuery(SQL.java:818)
java.lang.NullPointerException
        at oracle.dbtools.raptor.newscriptrunner.SQL.executeQuery(SQL.java:818)
        at oracle.dbtools.raptor.newscriptrunner.SQL.run(SQL.java:101)
        at oracle.dbtools.raptor.newscriptrunner.ScriptRunner.runSQL(ScriptRunner.java:433)
        at oracle.dbtools.raptor.newscriptrunner.ScriptRunner.run(ScriptRunner.java:250)
        at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:355)
        at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:238)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$23$681AAA$\^eval\_.handle(<eval>:38)
        at jdk.nashorn.javaadapters.oracle_dbtools_raptor_newscriptrunner_CommandListener.handleEvent(Unknown Source)
        at oracle.dbtools.raptor.newscriptrunner.CommandRegistry.fireListeners(CommandRegistry.java:448)
        at oracle.dbtools.raptor.newscriptrunner.ScriptRunner.run(ScriptRunner.java:241)
        at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:355)
        at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:238)
        at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.processLine(SqlCli.java:1142)
        at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.runSqlcl(SqlCli.java:1323)
        at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.main(SqlCli.java:350)

SQL> set sqlformat default
SQL Format Cleared
SQL> select * from dual;

D
-
X

SQL> pspg select * from dual;
2023-07-07 10:47:26.862 SEVERE oracle.dbtools.raptor.newscriptrunner.ScriptExecutor run oracle.dbtools.raptor.newscriptrunner.SQL.executeQuery(SQL.java:818)
java.lang.NullPointerException
        at oracle.dbtools.raptor.newscriptrunner.SQL.executeQuery(SQL.java:818)
        at oracle.dbtools.raptor.newscriptrunner.SQL.run(SQL.java:101)
        at oracle.dbtools.raptor.newscriptrunner.ScriptRunner.runSQL(ScriptRunner.java:433)
        at oracle.dbtools.raptor.newscriptrunner.ScriptRunner.run(ScriptRunner.java:250)
        at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:355)
        at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:238)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$23$681AAA$\^eval\_.handle(<eval>:38)
        at jdk.nashorn.javaadapters.oracle_dbtools_raptor_newscriptrunner_CommandListener.handleEvent(Unknown Source)
        at oracle.dbtools.raptor.newscriptrunner.CommandRegistry.fireListeners(CommandRegistry.java:448)
        at oracle.dbtools.raptor.newscriptrunner.ScriptRunner.run(ScriptRunner.java:241)
        at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:355)
        at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:238)
        at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.processLine(SqlCli.java:1142)
        at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.runSqlcl(SqlCli.java:1323)
        at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.main(SqlCli.java:350)

SQL> version
Oracle SQLDeveloper Command-Line (SQLcl) version: 23.2.0.0 build: 23.2.0.178.1029
```

Any ideas where the problem is or how to troubleshoot more?
Thank you!

**Comment by okbob** [comment]
Hi

pá 7. 7. 2023 v 10:49 odesílatel Alexandru Tică ***@***.***>
napsal:

> Hello,
>
> I'm trying to setup pspg in my sqlcl environment and I get the following
> error:
>
> SQL> set sqlformat ansiconsole
> SQL> select * from dual;
>
> DUMMY
> ________
> X
>
> SQL> pspg select * from dual;
> 2023-07-07 10:43:42.209 SEVERE oracle.dbtools.raptor.newscriptrunner.ScriptExecutor run oracle.dbtools.raptor.newscriptrunner.SQL.executeQuery(SQL.java:818)
> java.lang.NullPointerException
>         at oracle.dbtools.raptor.newscriptrunner.SQL.executeQuery(SQL.java:818)
>         at oracle.dbtools.raptor.newscriptrunner.SQL.run(SQL.java:101)
>         at oracle.dbtools.raptor.newscriptrunner.ScriptRunner.runSQL(ScriptRunner.java:433)
>         at oracle.dbtools.raptor.newscriptrunner.ScriptRunner.run(ScriptRunner.java:250)
>         at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:355)
>         at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:238)
>         at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$23$681AAA$\^eval\_.handle(<eval>:38)
>         at jdk.nashorn.javaadapters.oracle_dbtools_raptor_newscriptrunner_CommandListener.handleEvent(Unknown Source)
>         at oracle.dbtools.raptor.newscriptrunner.CommandRegistry.fireListeners(CommandRegistry.java:448)
>         at oracle.dbtools.raptor.newscriptrunner.ScriptRunner.run(ScriptRunner.java:241)
>         at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:355)
>         at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:238)
>         at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.processLine(SqlCli.java:1142)
>         at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.runSqlcl(SqlCli.java:1323)
>         at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.main(SqlCli.java:350)
>
> SQL> set sqlformat default
> SQL Format Cleared
> SQL> select * from dual;
>
> D
> -
> X
>
> SQL> pspg select * from dual;
> 2023-07-07 10:47:26.862 SEVERE oracle.dbtools.raptor.newscriptrunner.ScriptExecutor run oracle.dbtools.raptor.newscriptrunner.SQL.executeQuery(SQL.java:818)
> java.lang.NullPointerException
>         at oracle.dbtools.raptor.newscriptrunner.SQL.executeQuery(SQL.java:818)
>         at oracle.dbtools.raptor.newscriptrunner.SQL.run(SQL.java:101)
>         at oracle.dbtools.raptor.newscriptrunner.ScriptRunner.runSQL(ScriptRunner.java:433)
>         at oracle.dbtools.raptor.newscriptrunner.ScriptRunner.run(ScriptRunner.java:250)
>         at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:355)
>         at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:238)
>         at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$23$681AAA$\^eval\_.handle(<eval>:38)
>         at jdk.nashorn.javaadapters.oracle_dbtools_raptor_newscriptrunner_CommandListener.handleEvent(Unknown Source)
>         at oracle.dbtools.raptor.newscriptrunner.CommandRegistry.fireListeners(CommandRegistry.java:448)
>         at oracle.dbtools.raptor.newscriptrunner.ScriptRunner.run(ScriptRunner.java:241)
>         at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:355)
>         at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:238)
>         at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.processLine(SqlCli.java:1142)
>         at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.runSqlcl(SqlCli.java:1323)
>         at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.main(SqlCli.java:350)
>
> SQL> version
> Oracle SQLDeveloper Command-Line (SQLcl) version: 23.2.0.0 build: 23.2.0.178.1029
>
> Any ideas where the problem is or how to troubleshoot more?
> Thank you!
>

Maybe you don't have full configuration described in
https://github.com/okbob/pspg#sqlcl

**Comment by talek** [comment]
I invoke sqlcl using:

TTY=$(tty) sql /nolog @scripts/sqlcl/pspg.sql

Is there anything else to consider?

**Comment by okbob** [comment]
pá 7. 7. 2023 v 11:04 odesílatel Alexandru Tică ***@***.***>
napsal:

> I invoke sqlcl using:
>
> TTY=$(tty) sql /nolog @scripts/sqlcl/pspg.sql
>
> Is there anything else to consider?
>

Unfortunately, I don't know. Author of this script is Muhmud Ahmad. Maybe
some exception is raised there.

I know nothing about this environment, so I cannot help.
